// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACDKSyoAP0R4LOMV5shHFfyP_iTCQfVlE',
    appId: '1:59052659255:web:47d56a27e6b77380bb25b2',
    messagingSenderId: '59052659255',
    projectId: 'harboragekz',
    authDomain: 'harboragekz.firebaseapp.com',
    storageBucket: 'harboragekz.appspot.com',
    measurementId: 'G-9D3779GHHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArOXJtSeG52NEDGrOOsbXifngX2I-O3Pc',
    appId: '1:59052659255:android:60de82a6a3b429c9bb25b2',
    messagingSenderId: '59052659255',
    projectId: 'harboragekz',
    storageBucket: 'harboragekz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvt-mZUudP0oDZ80XqXGGpmnxF_ywWZwY',
    appId: '1:59052659255:ios:0532fa411c214da8bb25b2',
    messagingSenderId: '59052659255',
    projectId: 'harboragekz',
    storageBucket: 'harboragekz.appspot.com',
    iosBundleId: 'com.example.harboragekz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvt-mZUudP0oDZ80XqXGGpmnxF_ywWZwY',
    appId: '1:59052659255:ios:c0147236254daf34bb25b2',
    messagingSenderId: '59052659255',
    projectId: 'harboragekz',
    storageBucket: 'harboragekz.appspot.com',
    iosBundleId: 'com.example.harboragekz.RunnerTests',
  );
}
